name: React CI/CD Pipeline

on:
  push:
    branches:
      - main
      - release
      - develop

env:
  AZURE_STATIC_WEB_APPS_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_STATIC_WEB_APPS_NAME: ${{ secrets.AZURE_APP_NAME_PREFIX }}-${{ github.ref_name }}
  NODE_VERSION: "16.x" # Replace with your Node.js version
  BUILD_CONFIGURATION: "production"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set environment variables
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "REACT_APP_API_URL=https://api-prod.example.com" > .env
          elif [ "${{ github.ref_name }}" == "release" ]; then
            echo "REACT_APP_API_URL=https://api-uat.example.com" > .env
          else
            echo "REACT_APP_API_URL=https://api-dev.example.com" > .env
          fi
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "build"
          output_location: "" # Leave empty if no custom output location
          skip_app_build: true
